// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CreateFile: typeof import('./components/actions/CreateFile.vue')['default']
    CreateFolder: typeof import('./components/actions/CreateFolder.vue')['default']
    DeleteItem: typeof import('./components/actions/DeleteItem.vue')['default']
    FileEditor: typeof import('./components/FileEditor.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    TreeContainer: typeof import('./components/TreeContainer.vue')['default']
    TreeItem: typeof import('./components/TreeItem.vue')['default']
  }
}

export { }
